// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
	"VideoUtility": {
		"notice": "<b>¡Aviso!</b> Esta utilidad utiliza su CPU y RAM para procesar el video.<br></br><b>Esto puede afectar el rendimiento</b> y el procesamiento del video.",
		"loading": "Cargando utilidades. Por favor, espere...",
		"label": "Multiplicador de velocidad",
		"placeholder": "Multiplicador de velocidad",
		"transform": "Transformar video",
		"download": "Descargar resultado",
		"not_support": "Su navegador no admite la etiqueta de video.",
		"view_logs": "Ver registros de depuración",
		"log_title": "Registros",
		"close": "Cerrar",
		"or_choose_preset": "o elige un preset:",
		"video_label": "Video",
		"selected_video": "Video seleccionado:"
	},
	"microblog": {
		"placeholder": {
			"codeBlock": "Abrir la nota completa para ver el bloque de código",
			"table": "Abrir la nota completa para ver la tabla",
			"image": "Abrir la nota completa para ver la imagen"
		},
		"scrollToAttachment": "Desplazarse al adjunto",
		"outgoingLinks": "Enlaces salientes",
		"linkedNotes": "Notas enlazadas",
		"by": "por"
	},
	"NavigationMap": {
		"meta": {
			"title": "Mapa de Navegación",
			"description": "Explora el Mapa de Navegación de RevoTale. Descubre nuestras herramientas, utilidades y proyectos en formato visual."
		},
		"pageTitle": "Mapa de Navegación de RevoTale",
		"navigation": {
			"revotale": "RevoTale",
			"utilities": "Utilidades",
			"recordsRandomizer": "Selector Aleatorio de Registros",
			"urlEncoderDecoder": "Codificador/Decodificador de URL",
			"encode": "Codificar",
			"decode": "Decodificar",
			"screenFillGallery": "Galería de Pantalla Completa",
			"videoDurationChanger": "Cambiador de Velocidad de Video",
			"browserGames": "Juegos de Navegador",
			"battleShipGame": "Juego de Batalla Naval",
			"blog": "Blog",
			"articles": "Artículos",
			"notes": "Notas",
			"microTales": "Microrelatos",
			"selfHostedServices": "Servicios Auto-Hospedados",
			"tv": "TV",
			"dashboard": "Panel de Control",
			"personalNotes": "Notas Personales"
		}
	},
	"PageMeta": {
		"notes": {
			"title": "Notas - Codificación, Experiencia, Código Abierto, SEO y Conocimientos Científicos",
			"description": "Sumérgete en notas concisas llenas de consejos prácticos sobre codificación, rendimiento web, SEO, flujos de trabajo de IA, resúmenes de libros y más—actualizados regularmente en RevoTale."
		}
	},
	"LoveRain": {
		"meta": {
			"title": "Love Rain para tu persona especial",
			"description": "Una animación de neón en forma de corazón con gotas infinitas cayendo, renderizada en el navegador."
		}
	},
	"Project": {
		"title": "Revotale"
	},
	"keywords": {
		"url": "URL",
		"encode": "Codificar",
		"decode": "Decodificar",
		"online": "En línea"
	},
	"Metadata": {
		"Root": {
			"title": "Soluciones elegantes para tareas exigentes.",
			"desc": "Nuestro deseo es crear soluciones elocuentes utilizando las tecnologías más apropiadas y poderosas.",
			"openGraphDesc": "RevoTale es una empresa de software que se especializa en el desarrollo de aplicaciones web.",
			"classification": "Empresa de Software"
		},
		"Utils": {
			"title": "Utilidades",
			"desc": "Utilidades simples que te ayudan cuando las necesitas."
		},
		"BrowserGames": {
			"title": "Juegos de Navegador",
			"desc": "Juega juegos de navegador en línea sin descargas. Juegos ligeros que funcionan en cualquier dispositivo directamente en tu navegador."
		}
	},
	"Copy": {
		"text": "Copiar",
		"done": "¡Copiado! ✅",
		"error": "Error al escribir en el portapapeles"
	},
	"Paste": {
		"loading": "Procesando el portapapeles...",
		"text": "Pegar desde el portapapeles",
		"error": "Error al leer el portapapeles"
	},
	"UrlCoder": {
		"title": "Decodificar/Codificar URL",
		"metaDesc": "Codificador/decodificador de URL que te hace feliz. Serializa tu cadena al formato URL y viceversa.",
		"encode": "Codificar",
		"decode": "Decodificar",
		"inputPlace": "Escribe texto aquí",
		"outputPlace": "El resultado estará aquí",
		"same": "¡El resultado parece ser el mismo que la entrada! 🤔"
	},
	"ToolsBoard": {
		"Utilities": "Utilidades",
		"UtilitiesDesc": "Herramientas que simplifican la vida diaria de la persona promedio.",
		"Breadcrumbs": {
			"Utils": "Utilidades",
			"URlDecodeEncode": "Codificador/decodificador de URL",
			"VideoSpeedChange": "Cambiador de velocidad de video",
			"RecordRandomizer": "Aleatorizador de registros",
			"ImageCollectionTools": "Renderizador de colección de imágenes",
			"ScreenFillGallery": "Galería de Pantalla Completa",
			"encoder": "Codificador de URL",
			"decoder": "Decodificador de URL"
		},
		"Desc": {
			"URlDecodeEncode": "Herramienta simple para decodificar o codificar entidades URL sin conocimientos de programación.",
			"VideoSpeedChange": "Cambia la velocidad del video directamente en el navegador. Todo es manejado por la CPU/RAM de tu dispositivo. No se comparte ningún dato con ningún servidor porque el procesamiento de video se realiza gracias al poder de WASM en tu dispositivo.",
			"RecordRandomizer": "Ingresa la lista de registros, gira la rueda y obtén una línea seleccionada al azar. Perfecto para sorteos, toma de decisiones o cualquier situación donde se requiera una selección aleatoria rápida.",
			"ImageCollectionTools": "Llena cada centímetro con los medios que desees. Muestra cualquier número de imágenes en una sola pantalla.",
			"ScreenFillGallery": "Sube imágenes y llena toda tu pantalla con ellas de manera uniforme manteniendo las proporciones. Perfecto para crear galerías de fotos inmersivas."
		},
		"LearnMore": "Aprender más ➔"
	},
	"Breadcrumbs": {
		"blog": "Blog",
		"home": "Inicio",
		"utils": "Utilidades"
	},
	"ImageCollectionRenderer": {
		"title": "Renderizador de colección de imágenes",
		"seo_desc": "Renderiza tu colección de imágenes con comodidad. Cada centímetro de espacio está lleno",
		"seo_title": "Renderizador de colección de imágenes"
	},
	"ScreenFillGallery": {
		"title": "Galería de Pantalla Completa",
		"description": "Sube imágenes y llena toda tu pantalla con ellas manteniendo las proporciones. Perfecto para crear galerías de fotos inmersivas.",
		"seo_desc": "Llena tu pantalla de manera uniforme con imágenes manteniendo las proporciones. Crea hermosas galerías de fotos que aprovechan el espacio.",
		"seo_title": "Galería de Pantalla Completa - Distribución Uniforme de Imágenes",
		"imageLabel": "Seleccionar Imágenes",
		"fullscreenMode": "Modo Pantalla Completa",
		"imagesLoaded": "{count} imágenes cargadas",
		"keyword1": "galería pantalla completa",
		"keyword2": "galería de imágenes",
		"keyword3": "visor de fotos",
		"keyword4": "relación de aspecto",
		"keyword5": "imágenes pantalla completa",
		"keyword6": "colección de imágenes",
		"keyword7": "visualización de fotos",
		"keyword8": "imágenes responsivas",
		"applicationName": "Herramientas RevoTale",
		"category": "Tecnología",
		"classification": "Herramienta de Utilidad",
		"creator": "RevoTale",
		"publisher": "RevoTale"
	},
	"DurationConverter": {
		"seo_title": "Acelerar/ralentizar video en línea",
		"seo_desc": "Cambia la velocidad del video directamente en el navegador. Todo es manejado por la CPU/RAM de tu dispositivo. No se comparte ningún dato con ningún servidor porque el procesamiento de video se realiza gracias al poder de WASM en tu dispositivo."
	},
	"URLEncoder": {
		"seo_title": "Codificador de URL",
		"seo_desc": "Herramienta simple para decodificar o codificar entidades URL sin conocimientos de programación."
	},
	"URLDecoder": {
		"seo_title": "Decodificador de URL",
		"seo_desc": "Herramienta simple para decodificar o codificar entidades URL sin conocimientos de programación."
	},
	"Notes": {
		"title": "Notas",
		"title_blog": "Blog",
		"no_notes": "No hay notas todavía :(",
		"notes_heading": "Notas",
		"pagination": {
			"previous": "Anterior",
			"next": "Siguiente"
		},
		"json_ld": {
			"description": "Explora una colección de notas sobre varios temas, incluyendo codificación, rendimiento web, SEO, flujos de trabajo de IA y resúmenes de libros. Cada nota está diseñada para proporcionar información rápida y consejos prácticos para desarrolladores y entusiastas de la tecnología.",
			"name": "Notas"
		}
	},
	"Blog": {
		"meta_title": "Blog",
		"available_tags": "Etiquetas disponibles",
		"go_to_notes": "Notas",
		"go_to_micro_tales": "Ver microrelatos",
		"go_to_note": "Ver nota",
		"go_to_articles": "Artículos",
		"available_tag": "Etiquetas disponibles:",
		"meta_description": "Explora la intersección de tecnología, ciencia y sociedad con nuestros artículos estimulantes. Desde lo último en alta tecnología y avances en programación hasta discusiones perspicaces sobre política y experiencias personales, nuestro blog es un crisol de ideas diseñado para informar, inspirar y generar conversación. Únete a nosotros en un viaje a través del fascinante mundo de la innovación y el descubrimiento.",
		"latest_articles": "Lee los últimos artículos"
	},
	"HistoryOfUkraine": {
		"extendedInfo": "Información extendida",
		"title": "Historia de Ucrania",
		"meta_desc": "La historia de Ucrania en tesis cortas y simples. Fechas clave paso a paso. Prepárate fácilmente para el examen de Historia de Ucrania.",
		"table": {
			"date": "Fecha",
			"event": "Evento",
			"details": "Detalles",
			"importance": "Importancia"
		}
	},
	"Articles": {
		"title": "Artículos",
		"blog_crumb": "Blog"
	},
	"RandomRecordSelector": {
		"title": "Selector de registros aleatorios",
		"settings": "Configuración",
		"meta_desc": "Ingresa la lista de registros, gira la rueda y obtén una línea seleccionada al azar. Perfecto para sorteos, toma de decisiones o cualquier situación donde se requiera una selección aleatoria rápida.",
		"records": "Registros"
	},
	"ExpToolsBoard": {
		"desc": "Son muy inestables, están en desarrollo activo o no funcionan. ¯\\_(ツ)_/¯",
		"title": "Herramientas experimentales"
	},
	"OpenSource": {
		"desc": "Compartiendo el código con la comunidad de código abierto para ayudar al mundo a avanzar más rápido.",
		"title": "Código Abierto",
		"items": {
			"desc": {
				"obsidian_folder_by_tag_dist": "Ordena automáticamente tus notas de Obsidian Vault entre carpetas basadas en etiquetas. Esto te obliga a mantener coherente tu estructura de etiquetas y carpetas. Crea una estructura de directorios, coloca tus etiquetas, y tus notas se organizan automáticamente entre carpetas.",
				"google_recaptcha": "Integración invisible de Google reCAPTCHA en cualquier aplicación React <important>sin sacrificar la UX o la puntuación de velocidad de página.</important>",
				"lovely_eye": "Analítica de código abierto centrada en la privacidad, con un panel sencillo que puedes autoalojar.",
				"php_time": "Biblioteca para manejar problemas con las clases DateTime incorporadas de PHP. Maneja los tipos libremente y proporciona un enfoque directo a la relación entre objetos de tiempo, intervalo y zona horaria.",
				"nextjs_scroll_restorer": "Restaurador de desplazamiento para Next.js construido desde cero. Creado para uso en producción como reemplazo de la 'scrollRestoration' nativa en la configuración de Next.js, que es muy inestable."
			},
			"title": {
				"obsidian_folder_by_tag_dist": "Plugin distribuidor de carpetas por etiquetas de Obsidian",
				"google_recaptcha": "Google reCAPTCHA V3 para React",
				"lovely_eye": "Lovely Eye",
				"php_time": "PHP Time",
				"nextjs_scroll_restorer": "Restaurador de desplazamiento para Next.js"
			}
		}
	},
	"BlogBoard": {
		"title": "Blog",
		 "notes_title": "Descubrir notas",
		"desc": "Compartiendo cosas relacionadas con TI, noticias, ciencia, experiencias y pensamientos.",
		"explore": "Explora más artículos ➔",
		"welcome": "Nos alegramos de que estés aquí. ¡Disfrute de la lectura!",
		"discover_notes": "Descubrir notas",
		"read_latest_articles": "Leer los últimos artículos",
		"go_to_blog": "Ir al blog"
	},
	"RecordRandomizer": {
		"seo_title": "Aleatorizador de registros",
		"seo_desc": "Ingresa la lista de registros, gira la rueda y obtén una línea seleccionada al azar. Perfecto para sorteos, toma de decisiones o cualquier situación donde se requiera una selección aleatoria rápida.",
		"setting_seo_title": "Configuración del aleatorizador de registros",
		"setting_seo_desc": "Configuración del aleatorizador de registros. Ingresa la lista de registros, gira la rueda y obtén una línea seleccionada al azar. Perfecto para sorteos, toma de decisiones o cualquier situación donde se requiera una selección aleatoria rápida.",
		"setting_title": "Configuración del aleatorizador",
		"duration_setting_title": "Duración",
		"duration_setting_desc": "Tiempo en segundos después del cual la rueda debe detenerse",
		"setting_disable_winner_dialog_title": "Desactivar diálogo del ganador",
		"setting_disable_winner_dialog_desc": "Activa esta opción para desactivar la ventana emergente con el registro ganador.",
		"setting_save": "Guardar"
	},
	"Header": {
		"GoHome": "Ir a la página de inicio",
		"Search": "Buscar"
	},
	"Footer": {
		"Lang": {
			"en": "Inglés",
			"uk": "Ucraniano",
			"de": "Alemán",
			"fr": "Francés",
			"ja": "Japonés",
			"ru": "Ruso",
			"hi": "Hindi",
			"es": "Español"
		},
		"PoweredBy": "Nos preocupamos por tu privacidad. Las analíticas funcionan con <a>software de código abierto</a>.",
		"OpenNavMapButton": "Abrir Mapa de Navegación",
		"Utils": "Utilidades",
		"sea_battle": "Juego Clásico de Batalla Naval",
		"notes": "Notas",
		"sweetheart": "Para ti, corazoncito",
		"Blog": "Blog",
		"LangTitle": "Idiomas",
		"Rights": "© {year} {company}. Todos los derechos reservados.",
		"Nav": "Navegación",
		"TwitterAlt": "Síguenos en Twitter",
		"GithubAlt": "Califícanos en GitHub",
		"ReachOutTitle": "Contáctanos"
	},
	"SeaBattle": {
		"json_ld": {
			"name": "Juego de Batalla Naval",
			"description": "Un juego de Batalla Naval en tiempo real para dos jugadores, jugable en el navegador. Crea una sala, comparte un enlace con un amigo, coloca barcos y compite.",
			"serverName": "Crear Sala de Juego de Batalla Naval"
		},
		"howToPlay": {
			"title": "Sobre el juego",
			"step1": "No necesitas registrarte. Abre una sala y empezarás a jugar.",
			"step2": "Coloca los 10 barcos estándar, pulsa Listo y alternad disparos hasta hundir toda la flota del rival o la tuya.",
			"step3": "Invita a un amigo o juega contra un bot en nivel Fácil, Medio, Difícil o Hacker.",
			"step4": "Chat en tiempo real para comunicarte con tu oponente durante la partida."
		},
		"unknown_player_generic": "Jugador desconocido",
		"unknown_player_my": "Mi jugador desconocido",
		"unknown_player_enemy": "Jugador enemigo desconocido",
		"join_telegram": "¡Únete a una partida de Batalla Naval conmigo!",
		"title": "Batalla Naval",
		"pageDescription": "Juega a la Batalla Naval con tu amigo en el navegador en línea. Envía un enlace a tu amigo para jugar juntos.",
		"newGameWithFriend": "Iniciar un nuevo juego con un amigo",
		"newGameVsBot": "🤖 Jugar contra Bot",
		"or": "O",
		"loading": "Cargando...",
		"redirecting": "Redirigiendo a una sala...",
		"inviteFriend": "Invitar amigos",
		"inviteFriendDesc": "Comparte un enlace con tus amigos para jugar juntos",
		"CopyLink": "Copiar enlace",
		"facebook_icon": "Facebook",
		"whatsapp_icon": "WhatsApp",
		"telegram_icon": "Telegram",
		"players": {
			"title": "Jugadores"
		},
		"chat": {
			"button": "Chat",
			"dialogTitle": "Chat de la sala",
			"placeholder": "Escribe tu mensaje",
			"send": "Enviar",
			"empty": "Aún no hay mensajes",
			"newBadge": "Mensajes nuevos",
			"returnBackToShipLocating": "Vuelve a la colocación de barcos",
			"returnBackButtonSingle": "Volver",
			"returnBackToYourTurn": "¡Vuelve! ¡Es tu turno!",
			"returnBackToReadyToBattle": "¡Vuelve! ¡Tu oponente está listo!"
		},
		"room": {
			"title": "Sala de Batalla Naval"
		},
		"fight": {
			"title": "Combate de Batalla Naval",
			"view_battle": "Ver el campo de batalla",
			"enemy": "Campo enemigo",
			"your": "Tu campo",
			"yourTurn": "¡Tu turno! 💪",
			"enemyTurn": "Turno del enemigo 😈",
			"you_hit": "¡Has golpeado el barco! 💥",
			"you_missed": "¡Has fallado! 💦",
			"enemy_missed": "¡El enemigo falló! 💦",
			"enemy_hit_your_ship": "¡El enemigo golpeó tu barco! 💥",
			"waiting": "Esperando acción"
		},
		"shipLocating": {
			"title": "Ubicación de barcos de Batalla Naval"
		},
		"exit": "Salir de la sala",
		"ready": "Listo 💪",
		"not_ready": "No listo 🥥",
		"result": {
			"won": "¡Has ganado🎉!",
			"lost": "Has perdido la batalla...😔",
			"again": "¡Jugar de nuevo!"
		},
		"enter_name": "Ingresa un nuevo nombre de usuario",
		"update_username": "Cambiar nombre de usuario",
		"waiting_for_player": "Esperando a un jugador...",
		"waiting_for_another_p": "Esperando a otros jugadores para empezar",
		"start_battle": "¡Comienza una batalla!",
		"starting_game": "Iniciando juego...",
		"place_ship_title": "Coloca tus barcos",
		"place_ship_desc": "Solo arrástralos y suéltalos. ¡Puedes rotar un barco haciendo clic en él!",
		"randomize": "Aleatorizar barcos",
		"invalid_ships": "Colocación de barco inválida en columna #{x}, fila #{y}",
		"locating": {
			"start": "Guardar y comenzar una batalla",
			"waiting": "Esperando a que otro jugador coloque sus barcos..."
		},
		"addBot": {
			"emojiLabel": "robot",
			"button": "Agregar un Bot",
			"title": "Agregar Jugador Bot",
			"skillLabel": "Nivel de Dificultad del Bot",
			"cancel": "Cancelar",
			"loading": "Agregando Bot...",
			"confirm": "Agregar Bot"
		},
		"botSkill": {
			"easy": "Fácil",
			"easyDesc": "Bueno para principiantes",
			"average": "Medio",
			"averageDesc": "Juego equilibrado",
			"hard": "Difícil",
			"hardDesc": "Oponente desafiante",
			"hacker": "Hacker",
			"hackerDesc": "Desafío máximo"
		},
		"auth": {
			"cookiesDisabled": {
				"title": "Las cookies están desactivadas",
				"description": "<bold>¡Advertencia!</bold> Cuando recargue la página, se cerrará su sesión porque las cookies están desactivadas en su navegador. Por favor, habilite las cookies para mantener su sesión activa después de recargar la página."
			},
			"openInSystemBrowser": {
				"title": "Mejor experiencia disponible",
				"description": "Para una mejor experiencia de juego, por favor abra esta aplicación en su navegador del sistema.",
				"closeMessage": "Cerrar este mensaje",
				"openButton": "Abrir en el navegador del sistema",
				"openGameButton": "Abrir juego en el navegador del sistema"
			}
		}
	},
	"SeaBattleJoinLink": {
		"meta": {
			"title": "Unirse al juego de Batalla Naval",
			"description": "Únete a un juego de Batalla Naval a través del enlace de invitación. ¡Juega con tus amigos en tiempo real!",
			"ogTitle": "¡Únete a la Batalla Naval!",
			"ogDescription": "¡Haz clic en el enlace y juega Batalla Naval con tu amigo en tiempo real!",
			"ogImageAlt": "Juego de Batalla Naval"
		},
		"card": {
			"title": "Uniéndose a la batalla...",
			"errorTitle": "Error",
			"noCodeTitle": "Sin código de invitación",
			"noCodeDescription": "Por favor, usa un enlace de invitación válido para unirte a un juego.",
			"backToLobby": "Volver al lobby"
		}
	},
	"GamesBoard": {
		"title": "Juegos de Navegador",
		"desc": "¡Desarrollamos juegos para navegador para jugar en línea!",
		"sea_battle_desc": "¿Cansado de enviar mensajes de texto aburridos a tu amigo? ¡Envíale un enlace de invitación para unirse a una batalla naval contra ti! No se requiere descargar ninguna aplicación. ¡Juego ligero en el navegador para cualquier dispositivo!",
		"sea_battle": "Juego de Batalla Naval por Enlace"
	},
	"SelfHostList": {
		"title": "Servicios Autoalojados",
		"githubLink": "Abrir en GitHub",
		"desc": "Alojamiento propio de proyectos de código abierto para uso personal. ¡Mi agradecimiento a los autores y colaboradores de estos proyectos! ❤️",
		"items": {
			"title": {
				"watcharr": "Watcharr",
				"glance": "Gatus",
				"memos": "Memos"
			},
			"desc": {
				"glance": "Gatus es una página de estado orientada a desarrolladores que supervisa nuestros servicios con comprobaciones HTTP, ICMP, TCP y DNS, con alertas, y una vista pública del estado para que cualquiera pueda ver cuando un juego o servicio se cae.",
				"watcharr": "Watcharr es un proyecto de lista de seguimiento de código abierto y autoalojable para todo tu contenido (películas, series de televisión, anime, juegos), con autenticación de usuario, interfaz moderna y limpia, y una configuración muy sencilla.",
				"memos": "Memos es una solución ligera de toma de notas de código abierto. La manera más sencilla de crear tus notas más significativas. Tus notas, a tu manera."
			}
		}
	},
	"NotFound": {
		"title": "Algo falta.",
		"message": "Lo sentimos, no podemos encontrar esa página. Encontrarás mucho que explorar en la página de inicio.",
		"goHome": "Ir a la página de inicio."
	},
	"Error": {
		"title": "¡Error inesperado!"
	},
	"ImageCollection": {
		"imageLabel": "Imagen",
		"submit": "Enviar"
	},
	"copyButton":{
		"copy": "Copiar",
		"copied": "¡Copiado!"
	},
	"RandomizerWheel": {
		"restart_wheel": "Reiniciar la rueda",
		"close": "Cerrar",
		"winner_announcement": "¡Tenemos un ganador! 🎉"
	},
	"RssFeed": {
		"title": "Notas de RevoTale",
		"description": "Últimas notas y micro publicaciones de RevoTale",
		"generator": "Generador RSS de RevoTale",
		"authorName": "RevoTale",
		"authorEmail": "contact@revotale.com",
		"unknownAuthor": "Desconocido",
		"untitledNote": "Nota sin título",
		"internalServerError": "Error interno del servidor"
	}
};
export default messages;