FROM node:20.17-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY . .
RUN corepack enable pnpm && pnpm i
ARG SERVER_URL_ROOT
ARG SERVER_URL_PATH=''
ENV PAYLOAD_PUBLIC_SERVER_URL=$SERVER_URL_ROOT
ENV NEXT_PUBLIC_SERVER_URL="${SERVER_URL_ROOT}${SERVER_URL_PATH}"
ENV NODE_ENV=development
ENV PAYLOAD_SECRET=''
ENV DATABASE_URI=''
ENV NEXT_PUBLIC_IS_LIVE=1
ENV PAYLOAD_PUBLIC_DRAFT_SECRET='demo-draft-secret'
ENV NEXT_PRIVATE_DRAFT_SECRET='demo-draft-secret'
ENV REVALIDATION_KEY='demo-revalation-key'
ENV NEXT_PRIVATE_REVALIDATION_KEY='demo-revalation-key'

EXPOSE 3000
CMD ["pnpm", "dev"]
