FROM node:23-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY . .
RUN corepack enable pnpm && pnpm i
ARG SERVER_URL_ROOT
ARG SERVER_URL_PATH=''
ENV PAYLOAD_PUBLIC_SERVER_URL=$SERVER_URL_ROOT
ENV NEXT_PUBLIC_SERVER_URL="${SERVER_URL_ROOT}${SERVER_URL_PATH}"
ENV NODE_ENV=development
ENV PAYLOAD_SECRET=''
ENV DATABASE_URI=''
ENV NEXT_PUBLIC_IS_LIVE=1
ENV PAYLOAD_PUBLIC_DRAFT_SECRET='demo-draft-secret'
ENV NEXT_PRIVATE_DRAFT_SECRET='demo-draft-secret'
ENV REVALIDATION_KEY='demo-revalation-key'
ENV NEXT_PRIVATE_REVALIDATION_KEY='demo-revalation-key'
ENV S3_BUCKET=''
ENV S3_ENDPOINT=''

ENV S3_ACCESS_KEY_ID=''
ENV S3_SECRET_ACCESS_KEY=''
ENV S3_REGION=''

EXPOSE 3000
CMD pnpm install && pnpm dev
