FROM node:20.17-alpine
WORKDIR /home/node/app
COPY package.json  ./
COPY . .
RUN RUN corepack enable pnpm && pnpm i && pnpm build
ENV NODE_ENV=production
ENV PAYLOAD_SECRET=''
ENV DATABASE_URI=''
ENV PAYLOAD_PUBLIC_SERVER_URL=''
ENV NEXT_PUBLIC_SERVER_URL=$PAYLOAD_PUBLIC_SERVER_URL
ENV NEXT_PUBLIC_IS_LIVE=''
ENV PAYLOAD_PUBLIC_DRAFT_SECRET=''
ENV NEXT_PRIVATE_DRAFT_SECRET=''
ENV REVALIDATION_KEY=''
ENV NEXT_PRIVATE_REVALIDATION_KEY=''
EXPOSE 3000

CMD ["node", "dist/server.js"]
