server {
  listen 80;
  server_name _;

  resolver 127.0.0.11 valid=10s ipv6=off;
  resolver_timeout 5s;

  set $cms_upstream devcontainer:3000;
  set $imgproxy_upstream imgproxy:8080;
  set $rustfs_upstream rustfs:9000;

  location ~ ^/cdn/image/relative/(16|32|48|64|96|128|256|384|450|530|640|750|828|1080|1200|1920|2048|3840)/(.*)$ {
    proxy_pass http://$imgproxy_upstream/unsafe/width:$1/plain/http://$cms_upstream/$2$is_args$args;
  }

  location ~ ^/cdn/image/s3/(16|32|48|64|96|128|256|384|450|530|640|750|828|1080|1200|1920|2048|3840)/(.*)$ {
    proxy_pass http://$imgproxy_upstream/unsafe/width:$1/plain/http://$rustfs_upstream/cms/$2$is_args$args;
  }

  location / {
    proxy_http_version 1.1;
    proxy_pass http://$cms_upstream;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
