import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "posts" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "posts" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "posts" ALTER COLUMN "featured_image_id" SET DATA TYPE uuid;
  ALTER TABLE "posts_locales" ALTER COLUMN "meta_image_id" SET DATA TYPE uuid;
  ALTER TABLE "posts_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "posts_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "posts_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "posts_rels" ALTER COLUMN "tags_id" SET DATA TYPE uuid;
  ALTER TABLE "posts_rels" ALTER COLUMN "authors_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_posts_v" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v" ALTER COLUMN "version_featured_image_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_locales" ALTER COLUMN "version_meta_image_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "tags_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "authors_id" SET DATA TYPE uuid;
  ALTER TABLE "media" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "media" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "media_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "users_sessions" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "users" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "tags" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "tags" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "tags_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "authors" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "authors" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "authors" ALTER COLUMN "avatar_id" SET DATA TYPE uuid;
  ALTER TABLE "authors" ALTER COLUMN "user_id" SET DATA TYPE uuid;
  ALTER TABLE "authors_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_posts" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "micro_posts" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "micro_posts" ALTER COLUMN "attachment_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_posts_locales" ALTER COLUMN "meta_image_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_posts_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_posts_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_posts_rels" ALTER COLUMN "tags_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_posts_rels" ALTER COLUMN "micro_post_external_links_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_posts_rels" ALTER COLUMN "authors_id" SET DATA TYPE uuid;
  ALTER TABLE "_micro_posts_v" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_micro_posts_v" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_micro_posts_v" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_micro_posts_v" ALTER COLUMN "version_attachment_id" SET DATA TYPE uuid;
  ALTER TABLE "_micro_posts_v_locales" ALTER COLUMN "version_meta_image_id" SET DATA TYPE uuid;
  ALTER TABLE "_micro_posts_v_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_micro_posts_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_micro_posts_v_rels" ALTER COLUMN "tags_id" SET DATA TYPE uuid;
  ALTER TABLE "_micro_posts_v_rels" ALTER COLUMN "micro_post_external_links_id" SET DATA TYPE uuid;
  ALTER TABLE "_micro_posts_v_rels" ALTER COLUMN "authors_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_post_internal_links" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "micro_post_internal_links" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "micro_post_internal_links" ALTER COLUMN "source_note_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_post_internal_links" ALTER COLUMN "target_note_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_post_internal_links_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "micro_post_external_links" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "micro_post_external_links" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "micro_post_external_links_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "media_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "users_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "tags_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "authors_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "micro_posts_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "micro_post_internal_links_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "micro_post_external_links_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "users_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "posts" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "posts" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "posts" ALTER COLUMN "featured_image_id" SET DATA TYPE integer;
  ALTER TABLE "posts_locales" ALTER COLUMN "meta_image_id" SET DATA TYPE integer;
  ALTER TABLE "posts_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "posts_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "posts_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "posts_rels" ALTER COLUMN "tags_id" SET DATA TYPE integer;
  ALTER TABLE "posts_rels" ALTER COLUMN "authors_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_posts_v" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_posts_v" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v" ALTER COLUMN "version_featured_image_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_locales" ALTER COLUMN "version_meta_image_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "tags_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "authors_id" SET DATA TYPE integer;
  ALTER TABLE "media" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "media" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "media_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "users_sessions" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "users" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "tags" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "tags" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "tags_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "authors" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "authors" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "authors" ALTER COLUMN "avatar_id" SET DATA TYPE integer;
  ALTER TABLE "authors" ALTER COLUMN "user_id" SET DATA TYPE integer;
  ALTER TABLE "authors_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "micro_posts" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "micro_posts" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "micro_posts" ALTER COLUMN "attachment_id" SET DATA TYPE integer;
  ALTER TABLE "micro_posts_locales" ALTER COLUMN "meta_image_id" SET DATA TYPE integer;
  ALTER TABLE "micro_posts_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "micro_posts_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "micro_posts_rels" ALTER COLUMN "tags_id" SET DATA TYPE integer;
  ALTER TABLE "micro_posts_rels" ALTER COLUMN "micro_post_external_links_id" SET DATA TYPE integer;
  ALTER TABLE "micro_posts_rels" ALTER COLUMN "authors_id" SET DATA TYPE integer;
  ALTER TABLE "_micro_posts_v" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_micro_posts_v" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_micro_posts_v" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_micro_posts_v" ALTER COLUMN "version_attachment_id" SET DATA TYPE integer;
  ALTER TABLE "_micro_posts_v_locales" ALTER COLUMN "version_meta_image_id" SET DATA TYPE integer;
  ALTER TABLE "_micro_posts_v_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_micro_posts_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_micro_posts_v_rels" ALTER COLUMN "tags_id" SET DATA TYPE integer;
  ALTER TABLE "_micro_posts_v_rels" ALTER COLUMN "micro_post_external_links_id" SET DATA TYPE integer;
  ALTER TABLE "_micro_posts_v_rels" ALTER COLUMN "authors_id" SET DATA TYPE integer;
  ALTER TABLE "micro_post_internal_links" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "micro_post_internal_links" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "micro_post_internal_links" ALTER COLUMN "source_note_id" SET DATA TYPE integer;
  ALTER TABLE "micro_post_internal_links" ALTER COLUMN "target_note_id" SET DATA TYPE integer;
  ALTER TABLE "micro_post_internal_links_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "micro_post_external_links" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "micro_post_external_links" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "micro_post_external_links_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "media_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "users_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "tags_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "authors_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "micro_posts_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "micro_post_internal_links_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "micro_post_external_links_id" SET DATA TYPE integer;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "users_id" SET DATA TYPE integer;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" DROP DEFAULT;`)
}
