/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  uuid,
  boolean,
  varchar,
  timestamp,
  serial,
  integer,
  numeric,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum__locales = pgEnum('enum__locales', [
  'en-US',
  'uk-UA',
  'de-DE',
  'hi-IN',
  'ja-JP',
  'ru-RU',
  'fr-FR',
  'es-ES',
])
export const enum_posts_status = pgEnum('enum_posts_status', ['draft', 'published'])
export const enum__posts_v_version_status = pgEnum('enum__posts_v_version_status', [
  'draft',
  'published',
])
export const enum__posts_v_published_locale = pgEnum('enum__posts_v_published_locale', [
  'en-US',
  'uk-UA',
  'de-DE',
  'hi-IN',
  'ja-JP',
  'ru-RU',
  'fr-FR',
  'es-ES',
])
export const enum_micro_posts_status = pgEnum('enum_micro_posts_status', ['draft', 'published'])
export const enum__micro_posts_v_version_status = pgEnum('enum__micro_posts_v_version_status', [
  'draft',
  'published',
])
export const enum__micro_posts_v_published_locale = pgEnum('enum__micro_posts_v_published_locale', [
  'en-US',
  'uk-UA',
  'de-DE',
  'hi-IN',
  'ja-JP',
  'ru-RU',
  'fr-FR',
  'es-ES',
])

export const posts = pgTable(
  'posts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    featuredImage: uuid('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    meta_nofollow: boolean('meta_nofollow').default(false),
    meta_noindex: boolean('meta_noindex').default(false),
    authorSlug: varchar('author_slug'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    slug: varchar('slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_posts_status('_status').default('draft'),
  },
  (columns) => ({
    posts_featured_image_idx: index('posts_featured_image_idx').on(columns.featuredImage),
    posts_slug_idx: uniqueIndex('posts_slug_idx').on(columns.slug),
    posts_updated_at_idx: index('posts_updated_at_idx').on(columns.updatedAt),
    posts_created_at_idx: index('posts_created_at_idx').on(columns.createdAt),
    posts__status_idx: index('posts__status_idx').on(columns._status),
  }),
)

export const posts_locales = pgTable(
  'posts_locales',
  {
    title: varchar('title'),
    subtitle: varchar('subtitle'),
    content: varchar('content'),
    meta_title: varchar('meta_title'),
    meta_image: uuid('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    meta_description: varchar('meta_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => ({
    posts_meta_meta_image_idx: index('posts_meta_meta_image_idx').on(
      columns.meta_image,
      columns._locale,
    ),
    _localeParent: uniqueIndex('posts_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [posts.id],
      name: 'posts_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const posts_rels = pgTable(
  'posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    postsID: uuid('posts_id'),
    tagsID: uuid('tags_id'),
    authorsID: uuid('authors_id'),
  },
  (columns) => ({
    order: index('posts_rels_order_idx').on(columns.order),
    parentIdx: index('posts_rels_parent_idx').on(columns.parent),
    pathIdx: index('posts_rels_path_idx').on(columns.path),
    posts_rels_posts_id_idx: index('posts_rels_posts_id_idx').on(columns.postsID),
    posts_rels_tags_id_idx: index('posts_rels_tags_id_idx').on(columns.tagsID),
    posts_rels_authors_id_idx: index('posts_rels_authors_id_idx').on(columns.authorsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [posts.id],
      name: 'posts_rels_parent_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'posts_rels_posts_fk',
    }).onDelete('cascade'),
    tagsIdFk: foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'posts_rels_tags_fk',
    }).onDelete('cascade'),
    authorsIdFk: foreignKey({
      columns: [columns['authorsID']],
      foreignColumns: [authors.id],
      name: 'posts_rels_authors_fk',
    }).onDelete('cascade'),
  }),
)

export const _posts_v = pgTable(
  '_posts_v',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    parent: uuid('parent_id').references(() => posts.id, {
      onDelete: 'set null',
    }),
    version_featuredImage: uuid('version_featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_meta_nofollow: boolean('version_meta_nofollow').default(false),
    version_meta_noindex: boolean('version_meta_noindex').default(false),
    version_authorSlug: varchar('version_author_slug'),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_slug: varchar('version_slug'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__posts_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    snapshot: boolean('snapshot'),
    publishedLocale: enum__posts_v_published_locale('published_locale'),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => ({
    _posts_v_parent_idx: index('_posts_v_parent_idx').on(columns.parent),
    _posts_v_version_version_featured_image_idx: index(
      '_posts_v_version_version_featured_image_idx',
    ).on(columns.version_featuredImage),
    _posts_v_version_version_slug_idx: index('_posts_v_version_version_slug_idx').on(
      columns.version_slug,
    ),
    _posts_v_version_version_updated_at_idx: index('_posts_v_version_version_updated_at_idx').on(
      columns.version_updatedAt,
    ),
    _posts_v_version_version_created_at_idx: index('_posts_v_version_version_created_at_idx').on(
      columns.version_createdAt,
    ),
    _posts_v_version_version__status_idx: index('_posts_v_version_version__status_idx').on(
      columns.version__status,
    ),
    _posts_v_created_at_idx: index('_posts_v_created_at_idx').on(columns.createdAt),
    _posts_v_updated_at_idx: index('_posts_v_updated_at_idx').on(columns.updatedAt),
    _posts_v_snapshot_idx: index('_posts_v_snapshot_idx').on(columns.snapshot),
    _posts_v_published_locale_idx: index('_posts_v_published_locale_idx').on(
      columns.publishedLocale,
    ),
    _posts_v_latest_idx: index('_posts_v_latest_idx').on(columns.latest),
    _posts_v_autosave_idx: index('_posts_v_autosave_idx').on(columns.autosave),
  }),
)

export const _posts_v_locales = pgTable(
  '_posts_v_locales',
  {
    version_title: varchar('version_title'),
    version_subtitle: varchar('version_subtitle'),
    version_content: varchar('version_content'),
    version_meta_title: varchar('version_meta_title'),
    version_meta_image: uuid('version_meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_meta_description: varchar('version_meta_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => ({
    _posts_v_version_meta_version_meta_image_idx: index(
      '_posts_v_version_meta_version_meta_image_idx',
    ).on(columns.version_meta_image, columns._locale),
    _localeParent: uniqueIndex('_posts_v_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_posts_v.id],
      name: '_posts_v_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const _posts_v_rels = pgTable(
  '_posts_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    postsID: uuid('posts_id'),
    tagsID: uuid('tags_id'),
    authorsID: uuid('authors_id'),
  },
  (columns) => ({
    order: index('_posts_v_rels_order_idx').on(columns.order),
    parentIdx: index('_posts_v_rels_parent_idx').on(columns.parent),
    pathIdx: index('_posts_v_rels_path_idx').on(columns.path),
    _posts_v_rels_posts_id_idx: index('_posts_v_rels_posts_id_idx').on(columns.postsID),
    _posts_v_rels_tags_id_idx: index('_posts_v_rels_tags_id_idx').on(columns.tagsID),
    _posts_v_rels_authors_id_idx: index('_posts_v_rels_authors_id_idx').on(columns.authorsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_posts_v.id],
      name: '_posts_v_rels_parent_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: '_posts_v_rels_posts_fk',
    }).onDelete('cascade'),
    tagsIdFk: foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: '_posts_v_rels_tags_fk',
    }).onDelete('cascade'),
    authorsIdFk: foreignKey({
      columns: [columns['authorsID']],
      foreignColumns: [authors.id],
      name: '_posts_v_rels_authors_fk',
    }).onDelete('cascade'),
  }),
)

export const media = pgTable(
  'media',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    prefix: varchar('prefix').default('main_'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
  }),
)

export const media_locales = pgTable(
  'media_locales',
  {
    alt: varchar('alt').notNull(),
    description: varchar('description'),
    caption: varchar('caption'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex('media_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [media.id],
      name: 'media_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => ({
    _orderIdx: index('users_sessions_order_idx').on(columns._order),
    _parentIDIdx: index('users_sessions_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const users = pgTable(
  'users',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
  }),
)

export const tags = pgTable(
  'tags',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    tags_updated_at_idx: index('tags_updated_at_idx').on(columns.updatedAt),
    tags_created_at_idx: index('tags_created_at_idx').on(columns.createdAt),
  }),
)

export const tags_locales = pgTable(
  'tags_locales',
  {
    title: varchar('title').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex('tags_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tags.id],
      name: 'tags_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const authors = pgTable(
  'authors',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    slug: varchar('slug').notNull(),
    twitter_apiKey: varchar('twitter_api_key'),
    avatar: uuid('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    user: uuid('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    authors_slug_idx: uniqueIndex('authors_slug_idx').on(columns.slug),
    authors_avatar_idx: index('authors_avatar_idx').on(columns.avatar),
    authors_user_idx: index('authors_user_idx').on(columns.user),
    authors_updated_at_idx: index('authors_updated_at_idx').on(columns.updatedAt),
    authors_created_at_idx: index('authors_created_at_idx').on(columns.createdAt),
  }),
)

export const authors_locales = pgTable(
  'authors_locales',
  {
    name: varchar('name').notNull(),
    bio: varchar('bio'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex('authors_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [authors.id],
      name: 'authors_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const ai_call_logs = pgTable(
  'ai_call_logs',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    input: varchar('input').notNull(),
    output: varchar('output').notNull(),
    execution_time: numeric('execution_time').notNull(),
    user: uuid('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    ai_call_logs_user_idx: index('ai_call_logs_user_idx').on(columns.user),
    ai_call_logs_updated_at_idx: index('ai_call_logs_updated_at_idx').on(columns.updatedAt),
    ai_call_logs_created_at_idx: index('ai_call_logs_created_at_idx').on(columns.createdAt),
  }),
)

export const micro_posts = pgTable(
  'micro_posts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    attachment: uuid('attachment_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    slug: varchar('slug'),
    social_x_autoPost: boolean('social_x_auto_post').default(false),
    social_x_autoPosted: boolean('social_x_auto_posted').default(false),
    social_x_autoPostedAt: timestamp('social_x_auto_posted_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    authorSlug: varchar('author_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_micro_posts_status('_status').default('draft'),
  },
  (columns) => ({
    micro_posts_attachment_idx: index('micro_posts_attachment_idx').on(columns.attachment),
    micro_posts_slug_idx: uniqueIndex('micro_posts_slug_idx').on(columns.slug),
    micro_posts_updated_at_idx: index('micro_posts_updated_at_idx').on(columns.updatedAt),
    micro_posts_created_at_idx: index('micro_posts_created_at_idx').on(columns.createdAt),
    micro_posts__status_idx: index('micro_posts__status_idx').on(columns._status),
  }),
)

export const micro_posts_locales = pgTable(
  'micro_posts_locales',
  {
    title: varchar('title'),
    content: varchar('content'),
    meta_title: varchar('meta_title'),
    meta_image: uuid('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    meta_description: varchar('meta_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => ({
    micro_posts_meta_meta_image_idx: index('micro_posts_meta_meta_image_idx').on(
      columns.meta_image,
      columns._locale,
    ),
    _localeParent: uniqueIndex('micro_posts_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [micro_posts.id],
      name: 'micro_posts_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const micro_posts_rels = pgTable(
  'micro_posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagsID: uuid('tags_id'),
    micro_post_external_linksID: uuid('micro_post_external_links_id'),
    authorsID: uuid('authors_id'),
  },
  (columns) => ({
    order: index('micro_posts_rels_order_idx').on(columns.order),
    parentIdx: index('micro_posts_rels_parent_idx').on(columns.parent),
    pathIdx: index('micro_posts_rels_path_idx').on(columns.path),
    micro_posts_rels_tags_id_idx: index('micro_posts_rels_tags_id_idx').on(columns.tagsID),
    micro_posts_rels_micro_post_external_links_id_idx: index(
      'micro_posts_rels_micro_post_external_links_id_idx',
    ).on(columns.micro_post_external_linksID),
    micro_posts_rels_authors_id_idx: index('micro_posts_rels_authors_id_idx').on(columns.authorsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [micro_posts.id],
      name: 'micro_posts_rels_parent_fk',
    }).onDelete('cascade'),
    tagsIdFk: foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'micro_posts_rels_tags_fk',
    }).onDelete('cascade'),
    micro_post_external_linksIdFk: foreignKey({
      columns: [columns['micro_post_external_linksID']],
      foreignColumns: [micro_post_external_links.id],
      name: 'micro_posts_rels_micro_post_external_links_fk',
    }).onDelete('cascade'),
    authorsIdFk: foreignKey({
      columns: [columns['authorsID']],
      foreignColumns: [authors.id],
      name: 'micro_posts_rels_authors_fk',
    }).onDelete('cascade'),
  }),
)

export const _micro_posts_v = pgTable(
  '_micro_posts_v',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    parent: uuid('parent_id').references(() => micro_posts.id, {
      onDelete: 'set null',
    }),
    version_attachment: uuid('version_attachment_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_slug: varchar('version_slug'),
    version_social_x_autoPost: boolean('version_social_x_auto_post').default(false),
    version_social_x_autoPosted: boolean('version_social_x_auto_posted').default(false),
    version_social_x_autoPostedAt: timestamp('version_social_x_auto_posted_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_authorSlug: varchar('version_author_slug'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__micro_posts_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    snapshot: boolean('snapshot'),
    publishedLocale: enum__micro_posts_v_published_locale('published_locale'),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => ({
    _micro_posts_v_parent_idx: index('_micro_posts_v_parent_idx').on(columns.parent),
    _micro_posts_v_version_version_attachment_idx: index(
      '_micro_posts_v_version_version_attachment_idx',
    ).on(columns.version_attachment),
    _micro_posts_v_version_version_slug_idx: index('_micro_posts_v_version_version_slug_idx').on(
      columns.version_slug,
    ),
    _micro_posts_v_version_version_updated_at_idx: index(
      '_micro_posts_v_version_version_updated_at_idx',
    ).on(columns.version_updatedAt),
    _micro_posts_v_version_version_created_at_idx: index(
      '_micro_posts_v_version_version_created_at_idx',
    ).on(columns.version_createdAt),
    _micro_posts_v_version_version__status_idx: index(
      '_micro_posts_v_version_version__status_idx',
    ).on(columns.version__status),
    _micro_posts_v_created_at_idx: index('_micro_posts_v_created_at_idx').on(columns.createdAt),
    _micro_posts_v_updated_at_idx: index('_micro_posts_v_updated_at_idx').on(columns.updatedAt),
    _micro_posts_v_snapshot_idx: index('_micro_posts_v_snapshot_idx').on(columns.snapshot),
    _micro_posts_v_published_locale_idx: index('_micro_posts_v_published_locale_idx').on(
      columns.publishedLocale,
    ),
    _micro_posts_v_latest_idx: index('_micro_posts_v_latest_idx').on(columns.latest),
    _micro_posts_v_autosave_idx: index('_micro_posts_v_autosave_idx').on(columns.autosave),
  }),
)

export const _micro_posts_v_locales = pgTable(
  '_micro_posts_v_locales',
  {
    version_title: varchar('version_title'),
    version_content: varchar('version_content'),
    version_meta_title: varchar('version_meta_title'),
    version_meta_image: uuid('version_meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_meta_description: varchar('version_meta_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => ({
    _micro_posts_v_version_meta_version_meta_image_idx: index(
      '_micro_posts_v_version_meta_version_meta_image_idx',
    ).on(columns.version_meta_image, columns._locale),
    _localeParent: uniqueIndex('_micro_posts_v_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_micro_posts_v.id],
      name: '_micro_posts_v_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const _micro_posts_v_rels = pgTable(
  '_micro_posts_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagsID: uuid('tags_id'),
    micro_post_external_linksID: uuid('micro_post_external_links_id'),
    authorsID: uuid('authors_id'),
  },
  (columns) => ({
    order: index('_micro_posts_v_rels_order_idx').on(columns.order),
    parentIdx: index('_micro_posts_v_rels_parent_idx').on(columns.parent),
    pathIdx: index('_micro_posts_v_rels_path_idx').on(columns.path),
    _micro_posts_v_rels_tags_id_idx: index('_micro_posts_v_rels_tags_id_idx').on(columns.tagsID),
    _micro_posts_v_rels_micro_post_external_links_id_idx: index(
      '_micro_posts_v_rels_micro_post_external_links_id_idx',
    ).on(columns.micro_post_external_linksID),
    _micro_posts_v_rels_authors_id_idx: index('_micro_posts_v_rels_authors_id_idx').on(
      columns.authorsID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_micro_posts_v.id],
      name: '_micro_posts_v_rels_parent_fk',
    }).onDelete('cascade'),
    tagsIdFk: foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: '_micro_posts_v_rels_tags_fk',
    }).onDelete('cascade'),
    micro_post_external_linksIdFk: foreignKey({
      columns: [columns['micro_post_external_linksID']],
      foreignColumns: [micro_post_external_links.id],
      name: '_micro_posts_v_rels_micro_post_external_links_fk',
    }).onDelete('cascade'),
    authorsIdFk: foreignKey({
      columns: [columns['authorsID']],
      foreignColumns: [authors.id],
      name: '_micro_posts_v_rels_authors_fk',
    }).onDelete('cascade'),
  }),
)

export const micro_post_internal_links = pgTable(
  'micro_post_internal_links',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    source_note: uuid('source_note_id')
      .notNull()
      .references(() => micro_posts.id, {
        onDelete: 'set null',
      }),
    target_note: uuid('target_note_id')
      .notNull()
      .references(() => micro_posts.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    micro_post_internal_links_source_note_idx: index(
      'micro_post_internal_links_source_note_idx',
    ).on(columns.source_note),
    micro_post_internal_links_target_note_idx: index(
      'micro_post_internal_links_target_note_idx',
    ).on(columns.target_note),
    micro_post_internal_links_updated_at_idx: index('micro_post_internal_links_updated_at_idx').on(
      columns.updatedAt,
    ),
    micro_post_internal_links_created_at_idx: index('micro_post_internal_links_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const micro_post_internal_links_locales = pgTable(
  'micro_post_internal_links_locales',
  {
    title: varchar('title'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex('micro_post_internal_links_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [micro_post_internal_links.id],
      name: 'micro_post_internal_links_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const micro_post_external_links = pgTable(
  'micro_post_external_links',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    target_url: varchar('target_url').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    micro_post_external_links_target_url_idx: uniqueIndex(
      'micro_post_external_links_target_url_idx',
    ).on(columns.target_url),
    micro_post_external_links_updated_at_idx: index('micro_post_external_links_updated_at_idx').on(
      columns.updatedAt,
    ),
    micro_post_external_links_created_at_idx: index('micro_post_external_links_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const micro_post_external_links_locales = pgTable(
  'micro_post_external_links_locales',
  {
    title: varchar('title').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: uuid('_parent_id').notNull(),
  },
  (columns) => ({
    _localeParent: uniqueIndex('micro_post_external_links_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    _parentIdFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [micro_post_external_links.id],
      name: 'micro_post_external_links_locales_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    postsID: uuid('posts_id'),
    mediaID: uuid('media_id'),
    usersID: uuid('users_id'),
    tagsID: uuid('tags_id'),
    authorsID: uuid('authors_id'),
    ai_call_logsID: uuid('ai_call_logs_id'),
    micro_postsID: uuid('micro_posts_id'),
    micro_post_internal_linksID: uuid('micro_post_internal_links_id'),
    micro_post_external_linksID: uuid('micro_post_external_links_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_posts_id_idx: index(
      'payload_locked_documents_rels_posts_id_idx',
    ).on(columns.postsID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_tags_id_idx: index(
      'payload_locked_documents_rels_tags_id_idx',
    ).on(columns.tagsID),
    payload_locked_documents_rels_authors_id_idx: index(
      'payload_locked_documents_rels_authors_id_idx',
    ).on(columns.authorsID),
    payload_locked_documents_rels_ai_call_logs_id_idx: index(
      'payload_locked_documents_rels_ai_call_logs_id_idx',
    ).on(columns.ai_call_logsID),
    payload_locked_documents_rels_micro_posts_id_idx: index(
      'payload_locked_documents_rels_micro_posts_id_idx',
    ).on(columns.micro_postsID),
    payload_locked_documents_rels_micro_post_internal_links__idx: index(
      'payload_locked_documents_rels_micro_post_internal_links__idx',
    ).on(columns.micro_post_internal_linksID),
    payload_locked_documents_rels_micro_post_external_links__idx: index(
      'payload_locked_documents_rels_micro_post_external_links__idx',
    ).on(columns.micro_post_external_linksID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    tagsIdFk: foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'payload_locked_documents_rels_tags_fk',
    }).onDelete('cascade'),
    authorsIdFk: foreignKey({
      columns: [columns['authorsID']],
      foreignColumns: [authors.id],
      name: 'payload_locked_documents_rels_authors_fk',
    }).onDelete('cascade'),
    ai_call_logsIdFk: foreignKey({
      columns: [columns['ai_call_logsID']],
      foreignColumns: [ai_call_logs.id],
      name: 'payload_locked_documents_rels_ai_call_logs_fk',
    }).onDelete('cascade'),
    micro_postsIdFk: foreignKey({
      columns: [columns['micro_postsID']],
      foreignColumns: [micro_posts.id],
      name: 'payload_locked_documents_rels_micro_posts_fk',
    }).onDelete('cascade'),
    micro_post_internal_linksIdFk: foreignKey({
      columns: [columns['micro_post_internal_linksID']],
      foreignColumns: [micro_post_internal_links.id],
      name: 'payload_locked_documents_rels_micro_post_internal_links_fk',
    }).onDelete('cascade'),
    micro_post_external_linksIdFk: foreignKey({
      columns: [columns['micro_post_external_linksID']],
      foreignColumns: [micro_post_external_links.id],
      name: 'payload_locked_documents_rels_micro_post_external_links_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: uuid('users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const relations_posts_locales = relations(posts_locales, ({ one }) => ({
  _parentID: one(posts, {
    fields: [posts_locales._parentID],
    references: [posts.id],
    relationName: '_locales',
  }),
  meta_image: one(media, {
    fields: [posts_locales.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations_posts_rels = relations(posts_rels, ({ one }) => ({
  parent: one(posts, {
    fields: [posts_rels.parent],
    references: [posts.id],
    relationName: '_rels',
  }),
  postsID: one(posts, {
    fields: [posts_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
  }),
  tagsID: one(tags, {
    fields: [posts_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
  authorsID: one(authors, {
    fields: [posts_rels.authorsID],
    references: [authors.id],
    relationName: 'authors',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [posts.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  _locales: many(posts_locales, {
    relationName: '_locales',
  }),
  _rels: many(posts_rels, {
    relationName: '_rels',
  }),
}))
export const relations__posts_v_locales = relations(_posts_v_locales, ({ one }) => ({
  _parentID: one(_posts_v, {
    fields: [_posts_v_locales._parentID],
    references: [_posts_v.id],
    relationName: '_locales',
  }),
  version_meta_image: one(media, {
    fields: [_posts_v_locales.version_meta_image],
    references: [media.id],
    relationName: 'version_meta_image',
  }),
}))
export const relations__posts_v_rels = relations(_posts_v_rels, ({ one }) => ({
  parent: one(_posts_v, {
    fields: [_posts_v_rels.parent],
    references: [_posts_v.id],
    relationName: '_rels',
  }),
  postsID: one(posts, {
    fields: [_posts_v_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
  }),
  tagsID: one(tags, {
    fields: [_posts_v_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
  authorsID: one(authors, {
    fields: [_posts_v_rels.authorsID],
    references: [authors.id],
    relationName: 'authors',
  }),
}))
export const relations__posts_v = relations(_posts_v, ({ one, many }) => ({
  parent: one(posts, {
    fields: [_posts_v.parent],
    references: [posts.id],
    relationName: 'parent',
  }),
  version_featuredImage: one(media, {
    fields: [_posts_v.version_featuredImage],
    references: [media.id],
    relationName: 'version_featuredImage',
  }),
  _locales: many(_posts_v_locales, {
    relationName: '_locales',
  }),
  _rels: many(_posts_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_media_locales = relations(media_locales, ({ one }) => ({
  _parentID: one(media, {
    fields: [media_locales._parentID],
    references: [media.id],
    relationName: '_locales',
  }),
}))
export const relations_media = relations(media, ({ many }) => ({
  _locales: many(media_locales, {
    relationName: '_locales',
  }),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_tags_locales = relations(tags_locales, ({ one }) => ({
  _parentID: one(tags, {
    fields: [tags_locales._parentID],
    references: [tags.id],
    relationName: '_locales',
  }),
}))
export const relations_tags = relations(tags, ({ many }) => ({
  _locales: many(tags_locales, {
    relationName: '_locales',
  }),
}))
export const relations_authors_locales = relations(authors_locales, ({ one }) => ({
  _parentID: one(authors, {
    fields: [authors_locales._parentID],
    references: [authors.id],
    relationName: '_locales',
  }),
}))
export const relations_authors = relations(authors, ({ one, many }) => ({
  avatar: one(media, {
    fields: [authors.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
  user: one(users, {
    fields: [authors.user],
    references: [users.id],
    relationName: 'user',
  }),
  _locales: many(authors_locales, {
    relationName: '_locales',
  }),
}))
export const relations_ai_call_logs = relations(ai_call_logs, ({ one }) => ({
  user: one(users, {
    fields: [ai_call_logs.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_micro_posts_locales = relations(micro_posts_locales, ({ one }) => ({
  _parentID: one(micro_posts, {
    fields: [micro_posts_locales._parentID],
    references: [micro_posts.id],
    relationName: '_locales',
  }),
  meta_image: one(media, {
    fields: [micro_posts_locales.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations_micro_posts_rels = relations(micro_posts_rels, ({ one }) => ({
  parent: one(micro_posts, {
    fields: [micro_posts_rels.parent],
    references: [micro_posts.id],
    relationName: '_rels',
  }),
  tagsID: one(tags, {
    fields: [micro_posts_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
  micro_post_external_linksID: one(micro_post_external_links, {
    fields: [micro_posts_rels.micro_post_external_linksID],
    references: [micro_post_external_links.id],
    relationName: 'micro_post_external_links',
  }),
  authorsID: one(authors, {
    fields: [micro_posts_rels.authorsID],
    references: [authors.id],
    relationName: 'authors',
  }),
}))
export const relations_micro_posts = relations(micro_posts, ({ one, many }) => ({
  attachment: one(media, {
    fields: [micro_posts.attachment],
    references: [media.id],
    relationName: 'attachment',
  }),
  _locales: many(micro_posts_locales, {
    relationName: '_locales',
  }),
  _rels: many(micro_posts_rels, {
    relationName: '_rels',
  }),
}))
export const relations__micro_posts_v_locales = relations(_micro_posts_v_locales, ({ one }) => ({
  _parentID: one(_micro_posts_v, {
    fields: [_micro_posts_v_locales._parentID],
    references: [_micro_posts_v.id],
    relationName: '_locales',
  }),
  version_meta_image: one(media, {
    fields: [_micro_posts_v_locales.version_meta_image],
    references: [media.id],
    relationName: 'version_meta_image',
  }),
}))
export const relations__micro_posts_v_rels = relations(_micro_posts_v_rels, ({ one }) => ({
  parent: one(_micro_posts_v, {
    fields: [_micro_posts_v_rels.parent],
    references: [_micro_posts_v.id],
    relationName: '_rels',
  }),
  tagsID: one(tags, {
    fields: [_micro_posts_v_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
  micro_post_external_linksID: one(micro_post_external_links, {
    fields: [_micro_posts_v_rels.micro_post_external_linksID],
    references: [micro_post_external_links.id],
    relationName: 'micro_post_external_links',
  }),
  authorsID: one(authors, {
    fields: [_micro_posts_v_rels.authorsID],
    references: [authors.id],
    relationName: 'authors',
  }),
}))
export const relations__micro_posts_v = relations(_micro_posts_v, ({ one, many }) => ({
  parent: one(micro_posts, {
    fields: [_micro_posts_v.parent],
    references: [micro_posts.id],
    relationName: 'parent',
  }),
  version_attachment: one(media, {
    fields: [_micro_posts_v.version_attachment],
    references: [media.id],
    relationName: 'version_attachment',
  }),
  _locales: many(_micro_posts_v_locales, {
    relationName: '_locales',
  }),
  _rels: many(_micro_posts_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_micro_post_internal_links_locales = relations(
  micro_post_internal_links_locales,
  ({ one }) => ({
    _parentID: one(micro_post_internal_links, {
      fields: [micro_post_internal_links_locales._parentID],
      references: [micro_post_internal_links.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_micro_post_internal_links = relations(
  micro_post_internal_links,
  ({ one, many }) => ({
    source_note: one(micro_posts, {
      fields: [micro_post_internal_links.source_note],
      references: [micro_posts.id],
      relationName: 'source_note',
    }),
    target_note: one(micro_posts, {
      fields: [micro_post_internal_links.target_note],
      references: [micro_posts.id],
      relationName: 'target_note',
    }),
    _locales: many(micro_post_internal_links_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_micro_post_external_links_locales = relations(
  micro_post_external_links_locales,
  ({ one }) => ({
    _parentID: one(micro_post_external_links, {
      fields: [micro_post_external_links_locales._parentID],
      references: [micro_post_external_links.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_micro_post_external_links = relations(
  micro_post_external_links,
  ({ many }) => ({
    _locales: many(micro_post_external_links_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: 'tags',
    }),
    authorsID: one(authors, {
      fields: [payload_locked_documents_rels.authorsID],
      references: [authors.id],
      relationName: 'authors',
    }),
    ai_call_logsID: one(ai_call_logs, {
      fields: [payload_locked_documents_rels.ai_call_logsID],
      references: [ai_call_logs.id],
      relationName: 'ai_call_logs',
    }),
    micro_postsID: one(micro_posts, {
      fields: [payload_locked_documents_rels.micro_postsID],
      references: [micro_posts.id],
      relationName: 'micro_posts',
    }),
    micro_post_internal_linksID: one(micro_post_internal_links, {
      fields: [payload_locked_documents_rels.micro_post_internal_linksID],
      references: [micro_post_internal_links.id],
      relationName: 'micro_post_internal_links',
    }),
    micro_post_external_linksID: one(micro_post_external_links, {
      fields: [payload_locked_documents_rels.micro_post_external_linksID],
      references: [micro_post_external_links.id],
      relationName: 'micro_post_external_links',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum__locales: typeof enum__locales
  enum_posts_status: typeof enum_posts_status
  enum__posts_v_version_status: typeof enum__posts_v_version_status
  enum__posts_v_published_locale: typeof enum__posts_v_published_locale
  enum_micro_posts_status: typeof enum_micro_posts_status
  enum__micro_posts_v_version_status: typeof enum__micro_posts_v_version_status
  enum__micro_posts_v_published_locale: typeof enum__micro_posts_v_published_locale
  posts: typeof posts
  posts_locales: typeof posts_locales
  posts_rels: typeof posts_rels
  _posts_v: typeof _posts_v
  _posts_v_locales: typeof _posts_v_locales
  _posts_v_rels: typeof _posts_v_rels
  media: typeof media
  media_locales: typeof media_locales
  users_sessions: typeof users_sessions
  users: typeof users
  tags: typeof tags
  tags_locales: typeof tags_locales
  authors: typeof authors
  authors_locales: typeof authors_locales
  ai_call_logs: typeof ai_call_logs
  micro_posts: typeof micro_posts
  micro_posts_locales: typeof micro_posts_locales
  micro_posts_rels: typeof micro_posts_rels
  _micro_posts_v: typeof _micro_posts_v
  _micro_posts_v_locales: typeof _micro_posts_v_locales
  _micro_posts_v_rels: typeof _micro_posts_v_rels
  micro_post_internal_links: typeof micro_post_internal_links
  micro_post_internal_links_locales: typeof micro_post_internal_links_locales
  micro_post_external_links: typeof micro_post_external_links
  micro_post_external_links_locales: typeof micro_post_external_links_locales
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_posts_locales: typeof relations_posts_locales
  relations_posts_rels: typeof relations_posts_rels
  relations_posts: typeof relations_posts
  relations__posts_v_locales: typeof relations__posts_v_locales
  relations__posts_v_rels: typeof relations__posts_v_rels
  relations__posts_v: typeof relations__posts_v
  relations_media_locales: typeof relations_media_locales
  relations_media: typeof relations_media
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_tags_locales: typeof relations_tags_locales
  relations_tags: typeof relations_tags
  relations_authors_locales: typeof relations_authors_locales
  relations_authors: typeof relations_authors
  relations_ai_call_logs: typeof relations_ai_call_logs
  relations_micro_posts_locales: typeof relations_micro_posts_locales
  relations_micro_posts_rels: typeof relations_micro_posts_rels
  relations_micro_posts: typeof relations_micro_posts
  relations__micro_posts_v_locales: typeof relations__micro_posts_v_locales
  relations__micro_posts_v_rels: typeof relations__micro_posts_v_rels
  relations__micro_posts_v: typeof relations__micro_posts_v
  relations_micro_post_internal_links_locales: typeof relations_micro_post_internal_links_locales
  relations_micro_post_internal_links: typeof relations_micro_post_internal_links
  relations_micro_post_external_links_locales: typeof relations_micro_post_external_links_locales
  relations_micro_post_external_links: typeof relations_micro_post_external_links
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
