name: Test Suite

on:
  workflow_call:

permissions:
  contents: read

jobs:
  static-checks:
    runs-on: ubuntu-latest
    env:
      ROOT_WEBSITE_URL: https://revotale.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25.9.0"
      - name: Install pnpm
        run: npm install -g pnpm@11.5.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Task
        uses: go-task/setup-task@v2
      - run: task typegen
      - name: Validate
        run: task validate
      - name: Codegen check
        run: task codegen:check


  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Build Docker image
        run: docker build -f docker/Dockerfile .
